config/routes.rb
Rails.application.routes.draw do
  resources :songs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "songs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :song_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Spotify Analysis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1 class="font-bold text-4xl underline">スポティファイを分析する</h1>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :song_id, style: "display: block" %>
    <%= form.text_area :song_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p>
    <strong>Title:</strong>
    <%= song.title %>
  </p>

  <p>
    <strong>Song:</strong>
    <%= song.song_id %>
  </p>

</div>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Show this song", @song %> |
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/index.html.erb
<div class="flex justify-between items-center">
  <h2 class="font-bold text-3xl">再生曲ランキング</h2>
</div>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @song %>

<div>
  <%= link_to "Edit this song", edit_song_path(@song) %> |
  <%= link_to "Back to songs", songs_path %>

  <%= button_to "Destroy this song", @song, method: :delete %>
</div>